[package]
name = "rust_wasm_webpack_starter"
version = "0.1.0"
edition = "2021"
description = "rust wasm-webpack starter"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasm-bindgen = "0.2"
